apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fly-tunnel-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fly-tunnel-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  fly-api-token: {{ required "flyApiToken is required" .Values.flyApiToken | quote }}
  fly-app: {{ required "flyApp is required" .Values.flyApp | quote }}
  fly-region: {{ required "flyRegion is required" .Values.flyRegion | quote }}
