apiVersion: v2
name: fly-tunnel-operator
description: Kubernetes LoadBalancer operator using Fly.io Machines and frp tunnels
type: application
version: 0.0.0
appVersion: "0.0.0"
keywords:
  - kubernetes
  - loadbalancer
  - fly.io
  - frp
  - tunnel
  - homelab
home: https://github.com/zhming0/fly-tunnel-operator
sources:
  - https://github.com/zhming0/fly-tunnel-operator
